name: fridge_cook
description: A sample Flutter app demonstrating the usage of Clean Architecture and Test Driven Development for building iOS & Android applications using Image Recognition and ChatGPT ! - https://one-week-apps.com/fridge-cook/

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_clean_architecture: ^5.0.3
  flutter_launcher_icons:  ^0.9.0
  intl: ^0.16.1

  cached_network_image: ^3.2.3

  lottie: ^2.1.0

  google_fonts: ^2.1.0

  shared_preferences: ^2.0.15

  html: ^0.14.0+3
  http: ^0.13.0

  oktoast: ^3.3.1

dev_dependencies:
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/animations/Onboarding_Slide_Left_Arrows_Animation.json
    - assets/animations/Processing.json
    
    - assets/images/info.png
    - assets/images/scan.png
    - assets/images/filter.png
    - assets/images/plus.png
    - assets/images/my_products.png
    - assets/images/cooking.png
    - assets/images/my_recipes.png
    - assets/images/vegetables.png
    - assets/images/meat.png
    - assets/images/fish.png
    - assets/images/dairy.png
    - assets/images/fruits.png
    - assets/images/drinks.png
    - assets/images/cereals.png
    - assets/images/sugar.png
    - assets/images/food.png
    - assets/images/close.png

    - assets/images/clock.png
    - assets/images/difficulty.png
    - assets/images/people.png

    - assets/icon/icon.png
    - assets/images/star_off.png
    - assets/images/star_on.png
    - assets/images/fire.png
    - assets/images/cup.png
    - assets/images/trophy.png
    - assets/images/stats.png
    - assets/images/onboarding_scan.png
    - assets/images/onboarding_listing.png
    - assets/images/onboarding_recipes_listing.png
    - assets/images/onboarding_recipe_details.png
    - assets/images/unlocked.png
    - assets/images/placeholder_1.png
    - assets/images/placeholder_2.png
    - assets/images/like.png
    - assets/images/dislike.png
    - assets/images/achievements_view_outer.png
    - assets/images/achievements_background.png
    - assets/images/achievements_background_unlocked.png
    - assets/images/play_button.png
    - assets/images/salsa_coach_watch_1.png
    - assets/images/salsa_coach_watch_2.png
    - assets/images/trash.png
    - assets/images/achievement_trophy.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Luciole
      fonts:
        - asset: assets/fonts/Luciole-Regular.ttf
    - family: Salsa
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf
